- .circleci/config.yml
add ci/cd interation with circleci
> Ft integrate cirlce ci

- jest.config.js
- package.json
- pnpm-lock.yaml
- test/test.spec.ts
> ft: Unit testing setUp

- .env.example
- package.json
- pnpm-lock.yaml
- src/controllers/_index.ts
- src/controllers/user.controller.ts
- src/db/config.ts
- src/db/schemas/_index.ts
- src/db/schemas/user.schema.ts
- src/interfaces/_index.ts
- src/interfaces/userInterfaces.ts
- src/middleware/validation/_index.ts
- src/middleware/validation/user.schema.middleware.ts
- src/middleware/validation/validation.middleware.ts
- src/routes/_index.ts
- src/routes/user.routes.ts
- src/server.ts
- src/services/_index.ts
- src/services/user.service.ts
it will add database connection, add dummy user and tast user routes
> chore: add database connection

- src/controllers/user.controller.ts
- src/services/user.service.ts
fix typerror in the user.service.ts file and wherever else its called and imported... Also, this as a trial to test whether i'll be added as a contributor after i fixed my local git credentials
> fix: fix typerror in the user servise ts file

- test/test.spec.ts
> fx:fixing tests

- .circleci/config.yml
- src/db/config.ts
- test/test.spec.ts
add env variables and add create db cmd
add command create users
> fix: add load .env in development only

- .env.example
- README.md
- package.json
- updated the build script b'se previously it was failing when building (Issue was first raised by @ISINGIZWEcla ). The output dir i.e. `build` was mistyped.
- also update the README.md to account for all the 'currently' in-use keys.
> bg: update the build script, README.md, & .env.example

- .github/workflows/nodejs.yml
When a push event is detected on the main branch.
When a pull_request event is opened or synchronized (updated) on the main branch.
also I  chenge node version to meet the one we are using in project
> Fix workflows nodejs

- package.json
- src/app.ts
- src/controllers/Checkout.controller.ts
- src/routes/checkout.routes.ts
- src/routes/index.ts
- yarn.lock
I fixed memory leaks issue by storing session in the database. When a user Signs up or Logins, their sessions are automatically saved in DB, this implementation will help solve memory leaks issue. 
> fix: memory leaks fixes

- src/middleware/auth/passport.middleware.ts
- src/routes/passport.routes.ts
I have fixed the authentication using google and added suggested changes.
> fx: google authentication

- test/product.spec.ts
This will fix product tests that were previously not working due to the old codebase
#184361219
> fix: fix product tests

- docs/order.docs.yaml
- src/controllers/Order.controller.ts
- src/controllers/index.ts
- src/database/migrations/20230305181417-create-order-tables.js
- src/database/models/Order.model.ts
- src/routes/index.ts
- src/routes/order.routes.ts
- src/services/Order.service.ts
- src/services/index.ts
- test/order.spec.ts
In this feature, buyer can add create order status ofter he create cart, and he can track order status, Admin can change the order status and send update to the buyer profile
> ft:buyer view order status(add/get/delete)

- docs/wishes.docs.yaml
- src/controllers/Order.controller.ts
- src/controllers/Wish.controller.ts
- src/controllers/index.ts
- src/database/migrations/20230305183456-create-wishlist-tables.js
- src/database/models/Wishes.model.ts
- src/interfaces/Wish.interface.ts
- src/interfaces/index.ts
- src/routes/index.ts
- src/routes/wishes.routes.ts
- src/services/Wishes.services.ts
- src/services/index.ts
- test/wishes.spec.ts
In this feature, a buyer/ user can add a product to him/her wishlist, (add a product/ get a product and also delete a product from wishlist)
> feat: buyer can add product to wishlist(post,get and delete)

- docs/updatepassword.docs.yaml
- src/controllers/updatePassword.controller.ts
- src/database/migrations/20230227054250-create_users_table.js
- src/database/models/User.model.ts
- src/interfaces/User.interface.ts
- src/middleware/validation/user.schema.middleware.ts
- src/routes/auth.routes.ts
- test/updatePassword.spec.ts
GIVEN user is validly registered and account is validated. WHEN user/frontend provides old password, new password and confirm password fielated, or rejected due to the user ds THEN users new password should be hashed and updated, or rejected due to the user not remembering old password or new password and confirm password fields not matching.
This feature is fully documented and includes all of it's unit testing.
> ft: #184361217 add update password feature for user in case they want to.

- docs/resetPassword.docs.yaml
- src/controllers/Auth.controller.ts
- src/routes/auth.routes.ts
This will Add swagger documentation of the password reset via email feature.
#184361212
> docs(swagger): add docs of password reset [#184361212]

- .hound.yml
- docs/product.docs.yaml
- src/controllers/Product.controller.ts
- src/database/migrations/20230227054511-create_carts_table.js
- src/database/models/Cart.model.ts
- src/routes/product.routes.ts
- src/services/Product.service.ts
- test/auth.spec.ts
- test/product.spec.ts
- yarn.lock
In this feature, a seller sould delete a specific Item/product from collection
> ft:seller delete specific Item in collection

- Dockerfile
- docker-compose.yml
This changes setup the following services on local development:
1. express server
2. postgress db.
there is nothing worry on how heroku will run the app. this is only valid when we run locally, heroku will run the application in normal way
> ft: #184361206 Setup docker for backend application

- docs/product.docs.yaml
- src/controllers/Product.controller.ts
- src/routes/product.routes.ts
- src/services/Product.service.ts
This will add a way for users to view a specific product by its ID from the available products 
#184361222
> ft(product): add product view by ID [#184361222]

- .github/workflows/nodejs.yml
- docs/resetPassword.docs.yaml
- src/controllers/Auth.controller.ts
- src/controllers/User.controller.ts
- src/controllers/Wish.controller.ts
- src/middleware/auth/auth.middleware.ts
- src/routes/order.routes.ts
- src/routes/user.routes.ts
- src/routes/wishes.routes.ts
- src/services/User.service.ts
- src/services/protectRoutes.service.ts
- src/utils/jwt.utils.ts
- test/wishes.spec.ts
* This will fix a requested bug report where while resetting the password, a token should only be used once.
* This will also fix a requested bug report where the token to reset the password should have an expiry date
#184361212
> fix(utilsJWT): fix token expiry for password reset [#184361212]

- docs/order.docs.yaml
- src/controllers/Order.controller.ts
- src/database/migrations/20230305181417-create-order-tables.js
- src/database/models/Order.model.ts
- src/interfaces/Order.interface.ts
- src/interfaces/index.ts
- src/routes/order.routes.ts
- src/services/Order.service.ts
- test/order.spec.ts
In this feature, I added the root that allow admin to get all orders made by a buyer . also added order to display paymant status(which will be activated well when method of payment finished)
I also modify the way to get data in order so that the order will contain the detail of product and quantity
> #184361232 Feat:admin can get all orders

- jest.config.js
- src/controllers/Checkout.controller.ts
- src/database/config/config.js
- src/middleware/validation/checkout.schema.middleware.ts
- src/middleware/validation/index.ts
- src/routes/checkout.routes.ts
- test/cart.spec.ts
- test/twoFactorAuthentication.spec.ts
- test/updatePassword.spec.ts
- test/user.spec.ts
This P.R delivers the story #184361233, which is `Buyer should be able to make a payment using Stripe API` 💰
⚠️ 
- This is not test-able via the normal means, (ThunderClient, Swagger, or Postman), but you will need a working F.E to test the payment ft.)
- One thing to note too, is that we need to update the environment of the deployed API, and add the `STRIPE_SECRET`
> ft: #184361233 add payment using Stripe API

- docs/cart.docs.yaml
- src/controllers/Cart.controller.ts
- src/middleware/validation/product.schema.middleware.ts
- src/routes/cart.routes.ts
- src/services/Cart.service.ts
- test/cart.spec.ts
…84361230
ft: add cart feature(view/add/delete)
I have added new feature about buyer to update product in cart.
> #184361228 Feat:buyer should be able to update their cart

- docs/product.docs.yaml
- src/controllers/Product.controller.ts
- src/middleware/validation/product.schema.middleware.ts
- src/routes/product.routes.ts
- src/services/Product.service.ts
- test/product.spec.ts
fx: google authentication
I have added new feature for seller to update the product.
> #184361224 Feat: a seller should be able to update an product item from their collection

- src/controllers/Auth.controller.ts
- src/controllers/User.controller.ts
- src/database/migrations/20230227054250-create_users_table.js
- src/database/models/User.model.ts
- src/interfaces/User.interface.ts
- src/jobs/checkExpiredPasswords.ts
- src/jobs/index.ts
- src/services/User.service.ts
- src/services/mail/sendExpiredPasswordNotices.ts
- src/utils/checkLoginIntegrity.util.ts
- src/utils/index.ts
- test/auth.spec.ts
- test/twoFactorAuthentication.spec.ts
This P.R concludes the story #184361237, which is `User should be prompted to change their passwords every x amount of time since the time it was either manually updated.` 🔒 
It uses a cron job scheduled to run every 90 days at 17:30 (5:30 PM) to check for expired passwords, update the status of those which are, and send relevant emails to the owners of those passwords. 🔐 
> ft:#184361237 check for expired passwords - every 90 days 🔐  🦅 

- docs/notification.docs.yaml
- src/routes/index.ts
- src/routes/notification.routes.ts
* This will add a way for a user to view all notifications
* This will add a way for a user to read a specific notification
* This will also add a way for users to read all notifications
#184361235
> ft(notification): read all/a notification by ID [#184361235]

- src/controllers/Order.controller.ts
- src/controllers/Product.controller.ts
- src/interfaces/Order.interface.ts
- src/services/Order.service.ts
- test/order.spec.ts
In this feature, I have changed the way user and admin get orders so that It will be displayed as array instead of being string
>  #184361232 fx:change the way to get orders

- docs/disableAccount.docs.yaml
- src/controllers/AccountDisable.controller.ts
- src/controllers/index.ts
- src/database/migrations/20230312074609-modify_users_alter_column_status.js
- src/database/migrations/20230312080056-user_account_disabled_reasons.js
- src/database/models/DisabledAccount.model.ts
- src/interfaces/DisabledAccount.interface.ts
- src/interfaces/User.interface.ts
- src/interfaces/index.ts
- src/middleware/auth/auth.middleware.ts
- src/routes/accounts.routes.ts
- src/routes/index.ts
- src/services/protectRoutes.service.ts
- src/utils/checkLoginIntegrity.util.ts
- test/auth.spec.ts
- test/disableAccount.spec.ts
- test/user.spec.ts
add documentation and unit testing for this feature
WHEN a user is suspected or proved to have violated the terms of service of the application THEN admin is able to trigger an action to block usage of a particular account and an email sent to the user with reasons fro the block.
- [ x New and existing unit tests pass locally with my changes
> add ft: admin should be able to disable any user account #184361215

- .env.example
- docs/chat.docs.yaml
- jest.config.js
- package-lock.json
- package.json
- src/controllers/Chat.controller.ts
- src/database/migrations/20230311203450-create-chat-table.js
- src/database/models/Chat.model.ts
- src/interfaces/Chat.interface.ts
- src/interfaces/index.ts
- src/middleware/auth/socketAuth.middleware.ts
- src/routes/chat.routes.ts
- src/routes/index.ts
- src/server.ts
- test/chat.spec.ts
- yarn.lock
In this feature, Users should chat, get old messages, and post new messages
```
GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to read all of the past chats
GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to post a public chat
GIVEN the user
WHEN they post a chat
THEN it should be able to be echoed to all online users in realtime.
```
> #184361239 Feat: user chat 

- .github/workflows/nodejs.yml
- package.json
we were getting a green check mark indicating that tests were passing, though they were failing, this fix will stop coveralls reporting and will give a red failing cross on Github actions if tests are failing.
Fixes #123 
> fx: fix github actions tests failing reporting and coveralls

- src/app.ts
- src/controllers/Chat.controller.ts
- src/controllers/Notifications.controller.ts
- src/controllers/index.ts
- src/database/migrations/20230311203450-create-chat-table.js
- src/database/models/Chat.model.ts
- src/interfaces/Chat.interface.ts
- src/middleware/auth/socketAuth.middleware.ts
- src/server.ts
add peer to peer chatting
remove broadcasting message to all users
[loom video](https://www.loom.com/share/bdf491edd3ee4665b740c151f3c914dd)
> add chatting feature for users #184361239

- src/controllers/Auth.controller.ts
add redirect user to the deployed frontend login page
after successfully being registeresd , when user click the verification link in the email it should redirect to the deployed frontend login page
Fixes #121
> fx: redirect user to the deployed frontend login page #121
